[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "2021_2_dive"
path = "2021/2/dive.rs"

[lib]
name = "common"
path = "common/lib.rs"

[dependencies]
